apiVersion: apps.k8s.appscode.com/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: statefulset
    app.kubernetes.io/instance: statefulset-sample
    app.kubernetes.io/part-of: statefulset
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: statefulset
  name: statefulset-sample
spec:
  # TODO(user): Add fields here
